name: retworkx
channels:
  - defaults
  - conda-forge
dependencies:
  - rust=1.49.0
  - graphviz
  - pip
  - pip:
    - m2r2
    - jupyter-sphinx==0.2.3
    - pydot
    - pillow
    - qiskit-sphinx-theme>=1.7
    - reno>=3.2.0
    - matplotlib>=3.0
