---
notifications:
  email: false
os: linux
language: python
cache:
  pip: true
  cargo: true
dist: bionic
before_install:
  - which python
  - sh tools/install_rust.sh
  - export PATH=~/.cargo/bin:$PATH
  - which python
  - pip install -U pip virtualenv
install:
  - virtualenv test-venv
  - test-venv/bin/pip install -U .
script:
  - cd tests && ../test-venv/bin/python -m unittest discover .
stages:
  - name: Linux non-x86_64
    if: tag IS present
  - name: deploy
    if: tag IS blank

jobs:
  fast_finish: true
  allow_failures:
    - name: Python 3.7 Tests s390x Linux
  include:
    - name: Python 3.7 Tests ppc64le Linux
      stage: Linux non-x86_64
      python: 3.7
      arch: ppc64le
    - name: Python 3.7 Tests s390x Linux
      stage: Linux non-x86_64
      python: 3.7
      arch: s390x
    - name: Python 3.7 Tests arm64 Linux
      stage: Linux non-x86_64
      python: 3.7
      arch: arm64
    - stage: deploy
      arch: arm64
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && {package}/tools/install_rust.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust && bash {package}/tools/pgo/build_pgo.sh"
        - CIBW_SKIP="cp27-* cp34-* cp35-* pp*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin" RUSTFLAGS="-Cprofile-use=/tmp/pgo-data/merged.profdata"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - pip install -U twine importlib-metadata keyring cibuildwheel==1.6.4
        - cibuildwheel --output-dir wheelhouse
    - stage: deploy
      arch: ppc64le
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && {package}/tools/install_rust.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust && bash {package}/tools/pgo/build_pgo.sh"
        - CIBW_SKIP="cp27-* cp34-* cp35-* pp*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin" RUSTFLAGS="-Cprofile-use=/tmp/pgo-data/merged.profdata"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - pip install -U twine importlib-metadata keyring cibuildwheel==1.6.4
        - cibuildwheel --output-dir wheelhouse
    - stage: deploy
      arch: s390x
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && {package}/tools/install_rust_no_rustup.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust && bash {package}/tools/pgo/build_pgo.sh"
        - CIBW_SKIP="cp27-* cp34-* cp35-* pp*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin" RUSTFLAGS="-Cprofile-use=/tmp/pgo-data/merged.profdata"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - sudo pip install -U twine importlib-metadata keyring cibuildwheel==1.6.4
        - cibuildwheel --output-dir wheelhouse
